[package]
name = "wasm"
version = "0.1.0"
authors = ["Florian Mounier"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.70"
console_error_panic_hook = { version = "0.1.6", optional = true }
num-complex = "0.3.1"
rayon = "1.5.0"
rayon-core = "1.9.0"
futures-channel-preview = "0.3.0-alpha.18"
wasm-bindgen-futures = "0.4.20"
js-sys = "0.3.47"

[dev-dependencies]
wasm-bindgen-test = "0.3.20"

[profile.dev]
# Tell `rustc` to optimize for small code size.
opt-level = 3
lto = true

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
lto = true

[package.metadata.wasm-pack.profile.dev]
wasm-opt = ['-O4']

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false


[dependencies.web-sys]
version = "0.3.23"
features = [
  'CanvasRenderingContext2d',
  'ErrorEvent',
  'Event',
  'ImageData',
  'Navigator',
  'Window',
  'Worker',
  'DedicatedWorkerGlobalScope',
  'MessageEvent',
]
