export default {
  preset: 'RandomCube',
  remembered: {
    RandomCube: {
      0: {
        bloom: true,
        bloomStrength: 1.5,
        bloomRadius: 0.75,
        bloomThreshold: 0,
        bloomExposure: 0.75,
        afterImage: false,
        afterImageDamp: 0.75,
        configuration: 'randomCube',
        number: 1000,
        range: 1000,
        speed: 15,
        mass: 10,
        saturation: 1,
        luminance: 0.5,
        gravitationalConstant: 6.7,
        simulationSpeed: 0.5,
        collisions: true,
        collisionBase: 100,
        collisionScale: 100,
        escapeDistance: 10000,
      },
    },
    Galaxy: {
      0: {
        bloom: true,
        bloomStrength: 1.5,
        bloomRadius: 0.75,
        bloomThreshold: 0,
        bloomExposure: 0.75,
        afterImage: false,
        afterImageDamp: 0.75,
        configuration: 'proceduralDisc',
        number: 1000,
        range: 1000,
        speed: 15,
        mass: 100000,
        saturation: 1,
        luminance: 0.5,
        gravitationalConstant: 6.7,
        simulationSpeed: 0.5,
        collisions: false,
        collisionBase: 100,
        collisionScale: 100,
        escapeDistance: 10000,
      },
    },
  },
  closed: false,
  folders: {
    'Render fx': {
      preset: 'Default',
      closed: true,
      folders: {},
    },
    Configuration: {
      preset: 'Default',
      closed: false,
      folders: {},
    },
    Simulation: {
      preset: 'Default',
      closed: false,
      folders: {},
    },
  },
}
